config/routes.rb
Wakesurfers::Application.routes.draw do
  get "/wakesurfers", :controller=>"wakesurfers", :action=>"index", :as=>"wakesurfers"
  get "/wakesurfers/new", :controller=>"wakesurfers", :action=>"new", :as=>"wakesurfer_new"

  post "/wakesurfers", :controller=>"wakesurfers", :action=>"create"

  get "/wakesurfers/:id", :controller=>"wakesurfers", :action=>"show", :as=>"wakesurfer"

  delete "/wakesurfers/:id", :controller=>"wakesurfers", :action=>"destroy"

  get "/wakesurfers/edit/:id", :controller=>"wakesurfers", :action=>"edit", :as=>"edit_wakesurfer"
  put "/wakesurfers/:id", :controller=>"wakesurfers", :action=>"update"

end

app/models/wakesurfer.rb
class Wakesurfer < ActiveRecord::Base
  attr_accessible :title, :url
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/wakesurfers_controller.rb
class WakesurfersController < ApplicationController

	def index
		@wakesurfers = Wakesurfer.all
	end

	def show
		@wakesurfer = Wakesurfer.find_by_id(params[:id])
	end

	def new
		@wakesurfer = Wakesurfer.new
	end

	def create
		@wakesurfer = Wakesurfer.create(params[:wakesurfer])
		if @wakesurfer.save
			redirect_to wakesurfers_url
		else
			render 'new'
		end
	end

	def edit
		@wakesurfer = Wakesurfer.find_by_id(params[:id])
	end

	def update
		@wakesurfer = Wakesurfer.find_by_id(params[:id])
		@wakesurfer.url = params[:wakesurfer][:url]
		@wakesurfer.title = params[:wakesurfer][:title]
		if @wakesurfer.save
			redirect_to wakesurfers_url
		else
			render 'new'
		end
	end	

	def destroy
		p = Wakesurfer.find_by_id(params[:id])
		p.destroy
		redirect_to wakesurfers_url
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wakesurfers</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/wakesurfers/_form.html.erb
<%= form_for @wakesurfer do |wakesurfer| %>

	<%= wakesurfer.label :url, "Enter URL:" %>
	<%= wakesurfer.text_field :url, :size => 75 %>

	<%= wakesurfer.label :title, "Enter Title:" %>
	<%= wakesurfer.text_field :title, :size => 75 %>

	<%= wakesurfer.submit %>
	<%= link_to "Home", wakesurfers_url %>

<% end %>

app/views/wakesurfers/edit.html.erb
<h1>Edit you WakeSurfer</h1>

<%= render 'form' %>

app/views/wakesurfers/index.html.erb
<h1>Wakesurfer Collection</h1>

<h3>

<%= link_to "Add a New Wakesurfer", wakesurfer_new_url %>

</h3>

<ul>
<% @wakesurfers.each do |wakesurfer| %>
	
	<li>
	<%= link_to image_tag(wakesurfer.url, :width=>200), wakesurfer_url(wakesurfer.id) %>
	<%= link_to "Delete", wakesurfer_url(wakesurfer.id), :method=>"delete" %>
	<%= link_to "Edit", edit_wakesurfer_url(wakesurfer.id) %>
	</li>

<% end %>
</ul>

app/views/wakesurfers/new.html.erb
<h1>Add a new wakesurfer to your collection</h1>

<%= render 'form' %>

app/views/wakesurfers/show.html.erb
<%= image_tag(@wakesurfer.url) %>